name = "sakura-share-auth"
main = "worker.js"
compatibility_date = "2023-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "sakura-share"
database_id = "9fb790c8-d305-4739-b920-5693cb223bc4"

[placement]
mode = "smart"

[vars]
BOT_TOKEN = "7866348862:AAHgJIPOJlxEuHPoZOE59VaWCr0qwqJGTbM"
BOT_USERNAME = "SakuraShareBot"
TELEGRAM_SECRET_TOKEN = "Ag8qv0I2"